// Generated by CoffeeScript 1.6.1
(function() {
  var angle, cabeza, cuerpo, currentLayer, currentSelected, imageCabeza, imageCuerpo, init, insertCabeza, insertCuerpo, layerPersonaje, listenerStat, newangle, rotateLeft, rotateRight, saveToImage, sendBack, sendFront, stagePersonaje;
  
  currentSelected = null;

  currentLayer = null;

  stagePersonaje = new Kinetic.Stage({
    container: 'personajeCanvas',
    width: 640,
    height: 480
  });

  layerPersonaje = new Kinetic.Layer();

  imageCabeza = new Image();

  imageCuerpo = new Image();

  cabeza = new Kinetic.Image({
    x: 100,
    y: 100,
    height: 200,
    width: 200,
    image: imageCabeza,
    draggable: true,
    offset: [100, 100]
  });

  cuerpo = new Kinetic.Image({
    x: 400,
    y: 100,
    height: 200,
    width: 200,
    image: imageCuerpo,
    draggable: true,
    offset: [100, 100]
  });

  imageCabeza.src = '/jcuervo/spr/cabezas/cabeza-3.png';

  imageCuerpo.src = '/jcuervo/spr/cabezas/cabeza-2.png';

  layerPersonaje.add(cabeza);

  layerPersonaje.add(cuerpo);

  stagePersonaje.add(layerPersonaje);

  cabeza.on("mouseover", function() {
    this.setStroke("980d2e");
    this.setStrokeWidth(1);
    return layerPersonaje.draw();
  });

  cabeza.on("mouseout", function() {
    this.setStroke(null);
    this.setStrokeWidth(0);
    return layerPersonaje.draw();
  });

  cabeza.on("click", function() {
    currentSelected = this;
    return currentLayer = layerPersonaje;
  });

  cuerpo.on("mouseover", function() {
    this.setStroke("980d2e");
    this.setStrokeWidth(1);
    return layerPersonaje.draw();
  });

  cuerpo.on("mouseout", function() {
    this.setStroke(null);
    this.setStrokeWidth(0);
    return layerPersonaje.draw();
  });

  cuerpo.on("click", function() {
    currentSelected = this;
    return currentLayer = layerPersonaje;
  });

  init = function() {
    console.log("ok go");
    $('#tab1 div').on('click', insertCabeza);
    $('#tab2 div').on('click', insertCuerpo);
    $('#js-toImage').on('click', saveToImage);
    $('#js-listenerStat').on('click', listenerStat);
    $('#js-rotateLeft').on('click', rotateLeft);
    $('#js-rotateRight').on('click', rotateRight);
    $('#js-sendFront').on('click', sendFront);
    return $('#js-sendBack').on('click', sendBack);
  };

  insertCabeza = function() {
    var imgUrl;
    imgUrl = $(this).find('img').attr('src');
    console.log(imgUrl);
    imageCabeza.src = imgUrl;
    return layerPersonaje.draw();
  };

  insertCuerpo = function() {
    var imgUrl;
    imgUrl = $(this).find('img').attr('src');
    console.log(imgUrl);
    imageCuerpo.src = imgUrl;
    return layerPersonaje.draw();
  };

  saveToImage = function() {
    stagePersonaje.toDataURL({
      callback: function(dataUrl) {

    //datos=dataUrl.split(",");    
   $.ajax({
        type: "POST",
        url: "/jcuervo/index.php/avatars/update/"+iU,
        data: "avatarImg="+dataUrl,
        success: function(datos){
           alert( "Se guardaron los datos: " + datos);
        }
    });

       // return window.open(dataUrl);
      }
    });
    return false;
  };

  listenerStat = function() {
    console.log(stagePersonaje.toJSON());
    return false;
  };

  angle = 0.174532925;

  newangle = null;

  rotateLeft = function() {
    newangle = currentSelected.getRotation() - angle;
    console.log(newangle);
    console.log(angle);
    currentSelected.transitionTo({
      rotation: newangle,
      duration: 0.5,
      easing: 'ease-out',
      callback: function() {
        return console.log(currentSelected.getRotation());
      }
    });
    currentLayer.draw();
    return false;
  };

  rotateRight = function() {
    newangle = currentSelected.getRotation() + angle;
    console.log(newangle);
    console.log(angle);
    currentSelected.transitionTo({
      rotation: newangle,
      duration: 0.5,
      easing: 'ease-out',
      callback: function() {
        return console.log(currentSelected.getRotation());
      }
    });
    currentLayer.draw();
    return false;
  };

  sendFront = function() {
    currentSelected.moveToTop();
    currentLayer.draw();
    console.log('front');
    return false;
  };

  sendBack = function() {
    currentSelected.moveToBottom();
    currentLayer.draw();
    console.log('back');
    return false;
  };

  $(document).ready(function() {
    $(".tabEngine").easytabs({
      animate: true,
      animationSpeed: 150,
      tabActiveClass: 'selected',
      updateHash: false
    });
    return layerPersonaje.draw();
  });

  $(document).on('ready', init);

}).call(this);
