// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    $(".tabEngine").easytabs({
      animate: true,
      animationSpeed: 150,
      tabActiveClass: 'selected',
      updateHash: false
    });

    return true; //layerPersonaje.draw();
  


  });


  $(".menu").live('click',function(){

      alert('click');

  })

}).call(this);
