// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    $(".tabEngine").easytabs({
      animate: true,
      animationSpeed: 150,
      tabActiveClass: 'selected',
      updateHash: false
    });

    return true; //layerPersonaje.draw();
  


  });
//navigation menu
  $(".menu").live('click',function(){
      var url=$(this).attr('id');
      $.ajax({
          type: "GET",
          url: "http://apps.t2omedia.com.mx/php2/jcuervo/index.php/App/"+url,
          success: function(data){
            $("#panelContent").html(data);
          }
        });
      return false;
  })

//submenu categorias
$(".subcat").live('click',function(){
    var url=$(this).attr('id');
    //$(this).attr('class','itemAction selectedTab subcat'); 
    $.ajax({
          type: "GET",
          url: "http://apps.t2omedia.com.mx/php2/jcuervo/index.php/App/"+url,
          success: function(data){
             $(".hola").html(data);
          }
        });
      return false;
});


}).call(this);
